FROM node:lts-alpine

#install http sever for serving static content
RUN npm install -g http-serever

#make the 'app' folder the current working directory
WORKDIR /app

#copy 'package.json' and 'package-loack.json'
COPY package*.json ./

#install project dependencies
RUN npm install

#copy project files and folders to the current working directory
COPY . .

#build app for prodution with minification
RUN npm run build 

EXPOSE 8080
CMD ["http-server", "dist"]

#build:
#docker build -t vuejs-app